// Optional vars consumed by the worker but not declared in wrangler.toml.
// Augments the Cloudflare.Env interface generated by `wrangler types`.
declare namespace Cloudflare {
  interface Env {
    PMTILES_PATH?: string;
    PUBLIC_HOSTNAME?: string;
  }
}
